import Foundation

/// Book names and abbreviations in the big-8 languages (docs/localization.md), and which language
/// the app is naming books in right now.
///
/// **Why a process-wide setting.** A book's name is printed in two dozen places — the reader's
/// header, the passage picker, notes, cross-references, Listen, share cards, widgets — all through
/// `BookID.name`. Threading a language through every one of them would be a large change for no
/// gain: a process shows one Bible at a time, and the name should be that Bible's. So the reader
/// sets the language when the translation changes (`use(language:)`), and `BookID.name` answers in
/// it. English — every Bible without a language of its own — is the default.
///
/// The names are the ones each language's Bible prints (`BookNamesTable.swift`, generated by
/// Tools/build_book_names.py), so the interface calls a book what the text on screen does.
public enum BookNames {
    /// The languages there are names for, as used in `table`.
    public static var languages: [String] { Array(table.keys).sorted() }

    private static let lock = NSLock()
    nonisolated(unsafe) private static var currentLanguage: String?

    /// Names books in this language from now on; nil or an unknown language for English.
    /// Accepts any BCP 47 tag ("pt-BR", "zh-Hans-CN", "fr-CA").
    public static func use(language tag: String?) {
        let key = tag.flatMap(tableKey(for:))
        lock.withLock { currentLanguage = key }
    }

    /// The language books are named in, or nil for English.
    public static var current: String? { lock.withLock { currentLanguage } }

    /// The table key for a BCP 47 tag: its language, plus the script for Chinese (only Simplified
    /// has a table — a Traditional reader gets English names rather than the wrong script).
    public static func tableKey(for tag: String) -> String? {
        let language = Locale.Language(identifier: tag)
        guard let code = language.languageCode?.identifier else { return nil }
        if code == "zh" {
            let script = language.script?.identifier
                ?? Locale.Language(identifier: tag).maximalIdentifier.split(separator: "-").dropFirst().first.map(String.init)
            return script == "Hans" ? "zh-Hans" : nil
        }
        return table[code] != nil ? code : nil
    }

    static func name(_ book: BookID, in language: String? = current) -> String? {
        language.flatMap { table[$0]?[book.rawValue - 1].0 }
    }

    static func abbreviation(_ book: BookID, in language: String? = current) -> String? {
        language.flatMap { table[$0]?[book.rawValue - 1].1 }
    }

    /// Every normalized spelling a language accepts for each book: its names and abbreviations.
    static let aliases: [String: [BookID: Set<String>]] = {
        var result: [String: [BookID: Set<String>]] = [:]
        for (language, rows) in table {
            var books: [BookID: Set<String>] = [:]
            for (index, row) in rows.enumerated() {
                guard let book = BookID(rawValue: index + 1) else { continue }
                books[book] = Set(([row.0, row.1] + row.2).map(BookInfo.normalize))
            }
            result[language] = books
        }
        return result
    }()

    /// Spellings that mean different books in different languages ("es": Isaiah in French, Exodus in
    /// Italian). Only the current language — or English — may use them.
    static let ambiguous: Set<String> = {
        var owners: [String: Set<BookID>] = [:]
        for books in aliases.values {
            for (book, spellings) in books { for spelling in spellings { owners[spelling, default: []].insert(book) } }
        }
        for book in BookID.allCases { for spelling in book.info.aliases { owners[spelling, default: []].insert(book) } }
        return Set(owners.filter { $0.value.count > 1 }.keys)
    }()
}
