#!/bin/zsh
# Xcode Cloud post-clone. Generates the project, and writes the build-time content-key seed from
# the SA_CONTENT_KEY_SEED environment variable (set as a secret in the Xcode Cloud workflow).
#
# The seed is never in the repository. A build without the variable set produces a file with no
# seed, and the app simply has no content key — which is the correct state today, because every
# translation the app ships is public domain and none of them is encrypted.
set -euo pipefail
cd "$CI_PRIMARY_REPOSITORY_PATH"

brew install xcodegen
xcodegen generate

mkdir -p ScriptureAlone/Generated
SEED_FILE=ScriptureAlone/Generated/ContentKeySeed.swift

if [ -n "${SA_CONTENT_KEY_SEED:-}" ]; then
  # Stored as bytes XORed with a fixed pad. This is obfuscation, not protection: anyone who
  # disassembles the binary recovers it, and the white paper says so. It exists only so the seed
  # is not a plain string that `strings` prints for free.
  python3 - "$SA_CONTENT_KEY_SEED" > "$SEED_FILE" <<'PY'
import sys, hashlib
seed = bytes.fromhex(sys.argv[1]) if all(c in "0123456789abcdefABCDEF" for c in sys.argv[1]) else sys.argv[1].encode()
pad = hashlib.sha256(b"scripture-alone-seed-pad-v1").digest()
masked = bytes(b ^ pad[i % len(pad)] for i, b in enumerate(seed))
print("// Generated by ci_scripts/ci_post_clone.sh. Not in source control.")
print("import CryptoKit\nimport Foundation\n")
print("enum ContentKeySeed {")
print("    static let masked: [UInt8] = [" + ", ".join(f"0x{b:02x}" for b in masked) + "]")
print("""
    /// The seed, unmasked. Nil when the build carried none.
    static var data: Data? {
        guard !masked.isEmpty else { return nil }
        let pad = Array(SHA256.hash(data: Data("scripture-alone-seed-pad-v1".utf8)))
        return Data(masked.enumerated().map { $0.element ^ pad[$0.offset % pad.count] })
    }
}""")
PY
  echo "content key seed: written (${#SA_CONTENT_KEY_SEED} characters of input)"
else
  cat > "$SEED_FILE" <<'EMPTY'
// Generated by ci_scripts/ci_post_clone.sh. Not in source control.
import Foundation

enum ContentKeySeed {
    static let masked: [UInt8] = []
    /// No seed in this build: every bundled translation is public domain and unencrypted.
    static var data: Data? { nil }
}
EMPTY
  echo "content key seed: none set, wrote an empty seed"
fi
