#!/usr/bin/env python3
"""Writes ScriptureAlone/Generated/ContentKeySeed.swift from the SA_CONTENT_KEY_SEED environment variable.

    SA_CONTENT_KEY_SEED=… python3 ci_scripts/write_content_key_seed.py

Used by Xcode Cloud (ci_scripts/ci_post_clone.sh) and by a developer's local build
(Tools/prepare_licensed_local.sh), so both compile the seed the same way. Read from the environment,
never the command line, which other processes can see. Prints only whether a seed was written.

The seed is stored as bytes XORed with a fixed pad. This is obfuscation, not protection: anyone who
disassembles the binary recovers it, and the white paper says so. It exists only so the seed is not a
plain string that `strings` prints for free. Without a seed the file is still written, empty: every
bundled translation is then public domain.
"""

import hashlib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "ScriptureAlone", "Generated", "ContentKeySeed.swift")

raw = os.environ.get("SA_CONTENT_KEY_SEED", "")
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8") as out:
    out.write("// Generated by ci_scripts/write_content_key_seed.py. Not in source control.\n")
    if not raw:
        out.write("""import Foundation

enum ContentKeySeed {
    static let masked: [UInt8] = []
    /// No seed in this build: every bundled translation is public domain and unencrypted.
    static var data: Data? { nil }
}
""")
        print("content key seed: none set, wrote an empty seed")
        sys.exit(0)
    seed = bytes.fromhex(raw) if all(c in "0123456789abcdefABCDEF" for c in raw) else raw.encode()
    pad = hashlib.sha256(b"scripture-alone-seed-pad-v1").digest()
    masked = bytes(b ^ pad[i % len(pad)] for i, b in enumerate(seed))
    out.write("import CryptoKit\nimport Foundation\n\n")
    out.write("enum ContentKeySeed {\n")
    out.write("    static let masked: [UInt8] = [" + ", ".join(f"0x{b:02x}" for b in masked) + "]\n")
    out.write("""
    /// The seed, unmasked. Nil when the build carried none.
    static var data: Data? {
        guard !masked.isEmpty else { return nil }
        let pad = Array(SHA256.hash(data: Data("scripture-alone-seed-pad-v1".utf8)))
        return Data(masked.enumerated().map { $0.element ^ pad[$0.offset % pad.count] })
    }
}
""")
print(f"content key seed: written ({len(raw)} characters of input)")
