package com.blainemiller.scripturealone.data.canon

import java.util.Locale

/** One book's row in [BookNames]: its name as the language's Bible prints it, its standard abbreviation, other spellings. */
data class BookNameRow(val name: String, val abbreviation: String, val aliases: List<String>)

/**
 * Book names and abbreviations in the big-8 languages (docs/localization.md), and which language the
 * app is naming books in right now — `BookNames.swift` in ScriptureAloneCore.
 *
 * **Why a process-wide setting.** A book's name is printed in two dozen places — the reader's header,
 * the passage picker, notes, cross-references, Listen, share cards, widgets — all through
 * [BookID.displayName]. Threading a language through every one of them would be a large change for no
 * gain: a process shows one Bible at a time, and the name should be that Bible's. So the reader sets
 * the language when the translation changes ([use]), and [BookID.displayName] answers in it. English —
 * every Bible without a language of its own — is the default.
 *
 * The names are the ones each language's Bible prints (`BookNamesTable.kt`, generated by
 * Tools/build_book_names.py alongside the Swift table), so the interface calls a book what the text
 * on screen does.
 */
object BookNames {
    /** The languages there are names for, as used in the table. */
    val languages: List<String> get() = BOOK_NAMES_TABLE.keys.sorted()

    @Volatile private var currentLanguage: String? = null

    /** Names books in this language from now on; null or an unknown language for English. Any BCP 47 tag. */
    fun use(language: String?) {
        currentLanguage = language?.let(::tableKey)
    }

    /** The language books are named in, or null for English. */
    val current: String? get() = currentLanguage

    /**
     * The table key for a BCP 47 tag: its language, plus the script for Chinese (only Simplified has a
     * table — a Traditional reader gets English names rather than the wrong script).
     */
    fun tableKey(tag: String): String? {
        val locale = Locale.forLanguageTag(tag.replace('_', '-'))
        val code = locale.language.takeIf { it.isNotEmpty() } ?: return null
        if (code == "zh") {
            // Likely-subtags, as `maximalIdentifier` resolves them: Taiwan, Hong Kong and Macao write
            // Traditional; everywhere else Simplified.
            val script = locale.script.takeIf { it.isNotEmpty() }
                ?: if (locale.country in setOf("TW", "HK", "MO")) "Hant" else "Hans"
            return if (script == "Hans") "zh-Hans" else null
        }
        return if (BOOK_NAMES_TABLE.containsKey(code)) code else null
    }

    fun name(book: BookID, language: String? = current): String? =
        language?.let { BOOK_NAMES_TABLE[it]?.getOrNull(book.ordinal)?.name }

    fun abbreviation(book: BookID, language: String? = current): String? =
        language?.let { BOOK_NAMES_TABLE[it]?.getOrNull(book.ordinal)?.abbreviation }

    /** Every normalized spelling a language accepts for each book: its names and abbreviations. */
    val aliases: Map<String, Map<BookID, Set<String>>> by lazy {
        BOOK_NAMES_TABLE.mapValues { (_, rows) ->
            rows.mapIndexedNotNull { index, row ->
                val book = BookID.of(index + 1) ?: return@mapIndexedNotNull null
                book to (listOf(row.name, row.abbreviation) + row.aliases).map(BookID::normalize).toSet()
            }.toMap()
        }
    }

    /**
     * Spellings that mean different books in different languages ("es": Isaiah in French, Exodus in
     * Italian). Only the current language — or English — may use them.
     */
    val ambiguous: Set<String> by lazy {
        val owners = HashMap<String, MutableSet<BookID>>()
        for (books in aliases.values) {
            for ((book, spellings) in books) for (spelling in spellings) owners.getOrPut(spelling) { mutableSetOf() } += book
        }
        for (book in BookID.entries) for (spelling in book.aliases) owners.getOrPut(spelling) { mutableSetOf() } += book
        owners.filterValues { it.size > 1 }.keys
    }
}
