#!/usr/bin/env python3
"""Generates the Scripture Alone app icon: ScriptureAlone/Resources/AppIcon.icon.

    python3 Tools/generate_icon.py [path/to/AppIcon.icon]

"Book as horizon": a wide open book is the horizon, and a luminous half-sun
rises from its gutter. The design is kept to a few flat shapes; the depth
comes from Icon Composer's Liquid Glass layers, not from drawn detail.

Planes, front to back (each its own group in icon.json):

    Book   pages.svg   the open spread, white glass
           fold.svg    a thin line of light down the gutter
           leaves.svg  the page block just beneath the spread
           cover.svg   the cover, a little wider and lower still
    Sun    sun.svg     the half-sun, clipped where the pages cover it

The script writes both the SVG layers and icon.json (fills, glass and the
light / dark / tinted specializations), so edit it here, not in Icon Composer.
Preview with Icon Composer's renderer, e.g.

    ".../Icon Composer.app/Contents/Executables/ictool" AppIcon.icon --export-image \\
        --output-file out.png --platform iOS --rendition Dark --width 1024 --height 1024 --scale 1

Renditions: Default, Dark, TintedLight, TintedDark, ClearLight, ClearDark.
The same .icon serves iOS, iPadOS, macOS and (as a circle) watchOS.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ICON = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    HERE, "..", "ScriptureAlone", "Resources", "AppIcon.icon")

W = 1024
C = W / 2

# The open book. GUTTER_Y is the top of the fold; the pages rise from it to
# their outer edges (DIP higher), where each page lifts a little (CURL) and
# rounds over. PAGE_H is how much of each page's surface shows.
GUTTER_Y = 598
HALF_W = 404
DIP = 88
CURL = 16
PAGE_H = 118
CORNER = 30
RISE = 0.98           # how steeply the page leaves the fold (0..1)
LEAVE_X = 0.16        # ...and over what share of its width
LEAVES = (14, 5)      # page block: drop, extra width
COVER = (27, 13)      # cover: drop, extra width

SUN_R = 238

# Palette.
BG_LIGHT = ("#1F2257", "#7C4F7E")   # night indigo to dawn plum, top to bottom
BG_DARK = ("#08091C", "#2A1D3A")
SUN = ("#FFE9B0", "#FFA968")        # top of the disc, horizon


def fmt(v):
    return f"{v:.1f}".rstrip("0").rstrip(".")


def page_path(side, drop=0.0, grow=0.0):
    """One page (side -1 left, +1 right) of the spread, optionally shifted
    down by `drop` and widened by `grow` for the layers beneath it."""
    s = side
    gx, gy = C, GUTTER_Y + drop
    ox = C + s * (HALF_W + grow)
    oy = GUTTER_Y - DIP + drop
    span = HALF_W + grow
    c1 = (gx + s * span * LEAVE_X, gy - DIP * RISE)
    c2 = (gx + s * span * 0.70, oy + CURL * 0.2)
    tip = (ox - s * CORNER * 0.9, oy - CURL)          # the lifted corner
    h = PAGE_H
    p = [f"M{fmt(gx)} {fmt(gy)}",
         f"C{fmt(c1[0])} {fmt(c1[1])} {fmt(c2[0])} {fmt(c2[1])} {fmt(tip[0])} {fmt(tip[1])}",
         # round over the lifted corner onto the outer edge
         f"Q{fmt(ox)} {fmt(tip[1] - 2)} {fmt(ox)} {fmt(oy + CORNER * 0.6)}",
         f"L{fmt(ox)} {fmt(oy + h - CORNER)}",
         f"Q{fmt(ox)} {fmt(oy + h)} {fmt(ox - s * CORNER)} {fmt(oy + h)}",
         # the lower edge follows the upper one back to the fold
         f"C{fmt(c2[0])} {fmt(c2[1] + h - CURL * 0.2)} {fmt(c1[0])} {fmt(c1[1] + h)} {fmt(gx)} {fmt(gy + h)}",
         "Z"]
    return " ".join(p)


def spread(drop=0.0, grow=0.0):
    return (f'<path fill="#fff" d="{page_path(-1, drop, grow)}"/>'
            f'<path fill="#fff" d="{page_path(1, drop, grow)}"/>')


def top_edge_y(x):
    """y of the spread's upper edge at x (sampled from the Bezier)."""
    s = -1 if x < C else 1
    gx, gy = C, GUTTER_Y
    ox, oy = C + s * HALF_W, GUTTER_Y - DIP
    c1 = (gx + s * HALF_W * LEAVE_X, gy - DIP * RISE)
    c2 = (gx + s * HALF_W * 0.70, oy + CURL * 0.2)
    tip = (ox - s * CORNER * 0.9, oy - CURL)
    best = None
    for i in range(801):
        t = i / 800
        u = 1 - t
        px = u ** 3 * gx + 3 * u * u * t * c1[0] + 3 * u * t * t * c2[0] + t ** 3 * tip[0]
        py = u ** 3 * gy + 3 * u * u * t * c1[1] + 3 * u * t * t * c2[1] + t ** 3 * tip[1]
        if best is None or abs(px - x) < abs(best[0] - x):
            best = (px, py)
    return best[1]


def svg(body, defs="", note=""):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{W}" viewBox="0 0 {W} {W}">\n'
            f"<!-- Scripture Alone app icon: {note}. Generated by Tools/generate_icon.py. -->\n"
            f"<defs>{defs}</defs>\n{body}\n</svg>\n")


def sun_svg():
    # Clip the disc just below the pages' upper edge so nothing shows beneath the book.
    xs = range(int(C - HALF_W) + 6, int(C + HALF_W) - 5, 6)
    pts = [(x, top_edge_y(x) + 34) for x in xs]
    clip = (f"M0 0 H{W} V{fmt(pts[-1][1])} " + " ".join(f"L{fmt(x)} {fmt(y)}" for x, y in reversed(pts))
            + f" L0 {fmt(pts[0][1])} Z")
    defs = (f'<clipPath id="horizon"><path d="{clip}"/></clipPath>'
            f'<linearGradient id="sun" gradientUnits="userSpaceOnUse" x1="0" y1="{fmt(GUTTER_Y - SUN_R)}" '
            f'x2="0" y2="{fmt(GUTTER_Y)}"><stop offset="0" stop-color="{SUN[0]}"/>'
            f'<stop offset="1" stop-color="{SUN[1]}"/></linearGradient>')
    body = (f'<g clip-path="url(#horizon)"><circle cx="{fmt(C)}" cy="{fmt(GUTTER_Y)}" r="{SUN_R}" '
            f'fill="url(#sun)"/></g>')
    return svg(body, defs, "the half-sun rising from the gutter")


def fold_svg():
    top, bottom = GUTTER_Y - 4, GUTTER_Y + PAGE_H - 6
    defs = (f'<linearGradient id="fold" gradientUnits="userSpaceOnUse" x1="0" y1="{top}" x2="0" y2="{bottom}">'
            f'<stop offset="0" stop-color="{SUN[1]}"/><stop offset="1" stop-color="{SUN[1]}" stop-opacity="0"/>'
            f"</linearGradient>")
    body = f'<rect x="{fmt(C - 3)}" y="{top}" width="6" height="{bottom - top}" rx="3" fill="url(#fold)"/>'
    return svg(body, defs, "a line of light down the gutter")


def srgb(h, a=1.0):
    h = h.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    return f"srgb:{r:.5f},{g:.5f},{b:.5f},{a:.5f}"


def fills(light, dark, tinted=None):
    def v(x):
        return {"linear-gradient": [srgb(x[0]), srgb(x[1])]} if isinstance(x, tuple) else {"solid": srgb(x)}
    out = [{"value": v(light)}, {"appearance": "dark", "value": v(dark)}]
    if tinted is not None:
        out.append({"appearance": "tinted", "value": {"solid": f"extended-gray:{tinted:.5f},1.00000"}})
    return {"fill-specializations": out}


def icon_json():
    book = {
        "name": "Book",
        "lighting": "combined",
        "layers": [
            {"name": "fold", "image-name": "fold.svg",
             "hidden-specializations": [{"appearance": "tinted", "value": True}]},
            {"name": "pages", "image-name": "pages.svg", "glass": True,
             **fills(("#FFFFFF", "#F6EFE5"), ("#F2EDE6", "#D8D0C6"), 1.0)},
            {"name": "leaves", "image-name": "leaves.svg",
             **fills("#E6D8C4", "#B3A898", 0.72)},
            {"name": "cover", "image-name": "cover.svg",
             **fills("#C98F6B", "#7E5846", 0.45)},
        ],
        "shadow": {"kind": "neutral", "opacity": 0.5},
        "specular": True,
        "translucency": {"enabled": False, "value": 0.2},
    }
    sun = {
        "name": "Sun",
        "layers": [{"name": "sun", "image-name": "sun.svg", "glass": True,
                    "opacity-specializations": [{"appearance": "dark", "value": 0.85},
                                                {"appearance": "tinted", "value": 0.5}]}],
        "shadow": {"kind": "neutral", "opacity": 0.25},
        "specular": True,
        "translucency": {"enabled": True, "value": 0.1},
    }
    return {
        "fill-specializations": [
            {"value": {"linear-gradient": [srgb(BG_LIGHT[0]), srgb(BG_LIGHT[1])]}},
            {"appearance": "dark", "value": {"linear-gradient": [srgb(BG_DARK[0]), srgb(BG_DARK[1])]}},
        ],
        "groups": [book, sun],
        "supported-platforms": {"circles": ["watchOS"], "squares": "shared"},
    }


def main():
    assets = os.path.join(ICON, "Assets")
    os.makedirs(assets, exist_ok=True)
    for old in os.listdir(assets):
        os.remove(os.path.join(assets, old))
    layers = {
        "pages.svg": svg(spread(), note="the open spread"),
        "leaves.svg": svg(spread(*LEAVES), note="the page block beneath the spread"),
        "cover.svg": svg(spread(*COVER), note="the cover"),
        "fold.svg": fold_svg(),
        "sun.svg": sun_svg(),
    }
    for name, text in layers.items():
        with open(os.path.join(assets, name), "w") as fh:
            fh.write(text)
    with open(os.path.join(ICON, "icon.json"), "w") as fh:
        json.dump(icon_json(), fh, indent=2)
        fh.write("\n")
    print("wrote", os.path.normpath(ICON))


if __name__ == "__main__":
    main()
