#!/usr/bin/env python3
"""Google Play listing in the big-8 languages: android/play-metadata.md → play-metadata.<locale>.md.

    python3 Tools/translate_play_listing.py          # all eight
    python3 Tools/translate_play_listing.py fr-FR

The Play text differs from the App Store's (Wear OS, no iCloud), so it is translated from its own
English source, and adapted like the App Store copy (Tools/adapt_store_locales.py): each locale's
Bible named and downloaded on first launch, no commentary (English-only, hidden there), the Hebrew
and Greek word by word without a lexicon, no price or promotional words (Play flags them in the
short description), within Play's limits: title 30, short description 80, full description 4,000.
Only title, short_description, full_description and release_notes are written; the rest of the
English file (data safety, content rating…) is Play Console form answers, not listing text.
"""
import json, os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEVI = os.path.join(os.path.dirname(ROOT), "_shared", "levi", "levi.mjs")
SOURCE = os.path.join(ROOT, "android", "play-metadata.md")
LOCALES = {  # Play Console language codes
    "zh-CN": ("Simplified Chinese", "和合本（新标点）"),
    "ja-JP": ("Japanese", "文語訳聖書"),
    "de-DE": ("German", "Lutherbibel 1912"),
    "fr-FR": ("French", "Louis Segond 1910"),
    "es-ES": ("Spanish", "Reina-Valera 1909"),
    "ko-KR": ("Korean", "개역한글"),
    "pt-BR": ("Brazilian Portuguese", "Bíblia Livre"),
    "it-IT": ("Italian", "Riveduta 1927"),
}
LIMITS = {"title": 30, "short_description": 80, "full_description": 4000, "release_notes": 500}


def fields(text):
    return {m.group(1): re.sub(r"<!--.*?-->", "", m.group(2), flags=re.S).strip()
            for m in re.finditer(r"## (\w+)\n(.*?)(?=\n## |\Z)", text, re.S)}


def ask(prompt):
    for _ in range(4):
        try:
            out = subprocess.run(["node", LEVI, "ai", prompt], capture_output=True, text=True, timeout=420)
        except subprocess.TimeoutExpired:
            continue
        text = "\n".join(l for l in out.stdout.splitlines() if not l.startswith("▸"))
        start, end = text.find("{"), text.rfind("}")
        if start >= 0:
            try:
                return json.loads(text[start:end + 1])
            except json.JSONDecodeError:
                pass
    raise RuntimeError("no JSON from the model")


def translate(locale):
    language, bible = LOCALES[locale]
    english = fields(open(SOURCE, encoding="utf-8").read())
    source = {k: english[k] for k in LIMITS}
    prompt = (
        f"Localize this Google Play listing of a Bible app into {language} for a {language} reader. Translate "
        "faithfully and naturally, and adapt so every claim is true for them:\n"
        f"- Their Bible is the {bible}: downloaded on first launch, then read offline with its own book names and "
        "verse numbers; the English ASV, BSB and KJV are also available. The app is fully in their language.\n"
        "- The classic commentary (Calvin, Gill, Jamieson-Fausset-Brown) is NOT available in their language: "
        "remove it. Cross-references, maps, timeline and charts remain.\n"
        "- The Hebrew and Greek: word by word with parsing and Strong's numbers — no lexicon or definitions.\n"
        "- No price or promotional words anywhere (free, best, #1, no ads in the short description…).\n"
        f"- Limits in characters: {json.dumps(LIMITS)}.\n"
        'Return ONLY a JSON object with keys title, short_description, full_description, release_notes.\n\n'
        + json.dumps(source, ensure_ascii=False))
    for _ in range(3):
        out = ask(prompt)
        over = [k for k, n in LIMITS.items() if len(out.get(k, "")) > n or not out.get(k)]
        banned = [b for b in ("Calvin", "Gill", "Jamieson") if b in out.get("full_description", "")]
        if not over and not banned:
            break
        prompt = (f"Fix: fields over their limits or empty {over}; still mentions {banned}. Limits {json.dumps(LIMITS)}. "
                  "Return ONLY the corrected JSON object.\n\n" + json.dumps(out, ensure_ascii=False))
    else:
        raise SystemExit(f"{locale}: over={over} banned={banned}")
    path = os.path.join(ROOT, "android", f"play-metadata.{locale}.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"# Scripture Alone — Google Play listing ({language}, {locale})\n\n"
                "<!-- Generated by Tools/translate_play_listing.py from play-metadata.md; review before it ships. -->\n")
        for key in LIMITS:
            f.write(f"\n## {key}\n{out[key].strip()}\n")
    print(f"{locale}: " + ", ".join(f"{k} {len(out[k])}" for k in LIMITS))


if __name__ == "__main__":
    for locale in [a for a in sys.argv[1:] if a in LOCALES] or list(LOCALES):
        translate(locale)
